<template>
  <div class="xxx">
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
  </div>
</template>

<script>
export default {
  name: 'Admin',
  data () {
    return {}
  },
  created () {
    this.$axios
      .post('https://result.eolinker.com/Y9fD8sD59b6e75646e487c626b0b4aa09f83631ed98d005?uri=/user/login', res => {
        console.log(res)
      })
  }
}
</script>
